### ISSUE TITLE
How can I import a resource? 

### ISSUE THREAD

**Issue by JudMartinez** [obiba/opal-python-client#36]
Hi, 

I've been looking at the issues and I don't quite understand _how can I import a resource into Opal using python_? 

Thanks!

**Comment by kazoompa** [comment]
Hi,

Do you mean the data associated with a resource? That is not supported due to the fact that Opal databases are for general purpose and do not properly manage large amounts of information. Current suppored imports via Python are listed [here](https://opaldoc.obiba.org/en/latest/python-user-guide/import/index.html?highlight=import%20resource) .

Maybe you can explain why you wish to import a resource via Python.

Best,

**Comment by kazoompa** [comment]
You can Use the [RESTService](https://github.com/obiba/opal-python-client/blob/master/obiba_opal/system.py#L375) and write your own script. One easy way is to use the browser Dev Tool (XHR Tab) and create a dummy resource to see what is send to opal.

Here is an example of what you need:
- URL: `https://opal-demo.obiba.org/ws/project/FNAC/resources`
- HTTP Method:  `POST`
- Content Type: `application/x-protobuf+json`
- Content Body: 
```json
{
    "name": "Test",
    "description": "Bla bla",
    "project": "FNAC",
    "provider": "resourcer",
    "factory": "opal-rdata-file",
    "parameters": "{\"url\":\"https://opal-demo.obiba.org\", \"path\":\"/tmp/test\", \"format\":\"testObject\"}",
    "credentials": "{\"token\":\"BLABLABLABLABLA\"}"
}
```

Here is more [info](https://opaldoc.obiba.org/en/latest/python-user-guide/other/rest.html?highlight=python%20rest).

**Comment by JudMartinez** [comment]
I have been trying what you told me and I get a 405 error: "_Error 405 HTTP method POST is not supported by this URL_".

Do you know if the problem is that OPAL does not allow a POST method in resources? Or is it something else?

Thanks, 

Judith

**Comment by kazoompa** [comment]
Here is an example:
```
opal rest "/project/FNAC/resources" -o https://opal-demo.obiba.org -u administrator -p password -m POST  -ct application/json < /tmp/opal-resurce.json
```
